import Head from 'next/head'
import styles from '../styles/Home.module.css'

import EnergieSelect from '../components/energies/energieSlect/energieSelect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Production Electrique en France</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <EnergieSelect />
    </>


  )
}
