import {useRouter} from 'next/router'

import styles from './energie.module.sass'

import Head from 'next/head'
import palette from '../../components/palette/palette'

import filliereProd from '../../components/listProducteur/listProducteur'
import Pins from '../../components/pins/pins'

import Nav from '../../components/nav/nav'
import Dashboard from '../../components/dashboard/dashboard'

import Footer from '../../components/footer/footer'

export default function Home() {

  const router = useRouter();
  const { type } = router.query;

  const style= {
    background: palette[0],
    color: palette[0]
  };

  const styleHeader= {
    background: palette[0],
    color: palette[2]
  }

  return (
    <>
      <Head>
        <title>Analyse de l'énergie {filliereProd[type]}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header} style={styleHeader}>

        <figure className={styles.figure} >

          <Pins src={"/images/home/home.svg"} title="Accueil" color={palette} link="../"/>  

        </figure>

        <h1 className={styles.titre}>Tableau de bord</h1>

      </header>

      <section className={styles.container} style={style}>
        <Nav type={type}/>

        <Dashboard type={type}/>

      </section>

      <Footer />
      
    </>


  )
}