import {useRouter} from 'next/router'

import styles from './energie.module.sass'

import Head from 'next/head'
import palette from '../../components/palette/palette'

import filliereProd from '../../components/listProducteur/listProducteur'

import Handler from '../../components/handlerDataView/handlerdataView'


export default function Home() {

  const router = useRouter();
  const { type } = router.query;

  const style= {
    background: palette[0],
    color: palette[2]
  };

  return (
    <>
      <Head>
        <title>Analyse de l'énergie {filliereProd[type]}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section style={style}>

        <article className={styles.graphContainer}>

          <Handler type={type} items={"graph"} />

        </article>
        <article className={styles.graphContainer}>

          <Handler type={type} items={"donut"} />

        </article>
        <article className={styles.graphContainer}>

          <Handler type={type} items={"donutF5"} />

        </article>
        <article className={styles.graphContainer}>

          <Handler type={type} items={"bar"} />

        </article>

      </section>

    </>


  )
}